# Generated by Django 3.1.5 on 2021-02-01 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pocketchef_receitas', '0003_receita_publicada'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='foto_receita',
            field=models.ImageField(blank=True, upload_to='fotos/%d/%m/%Y/'),
        ),
    ]
